site_name: Tube8·(中国区) 日本网站-入口
site_author: Tube8
site_description: Tube8·(中国区)官方网站-入口 Tube8,Tube8入口是官方网站✌️Tube8日本入口 路灯推荐✌️, 回家的路 需要你我他指引路灯!
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
